<h1 class="title">About Catherine Musemeche</h1>
<p><a title="Dr. Kate" href="images/drkate.jpg" rel="lightbox"><img class="framed imageLeft" src="/images/drkate_sized.jpg" alt="Dr. Catherine Musemeche, M.D."></a> It takes a decade of training to become a pediatric surgeon. Catherine Musemeche has been one for twenty years.</p>
<!-- 
<a title="A portrait of Dr. Kate Musemeche, MD." href="images/Kate_Musemeche_bio_full.jpg" rel="lightbox">
<img class="framed imageLeft" src="images/Kate_Musemeche_bio.jpg" alt="Dr. Kate Musemeche, MD, pediatric surgeon" /></a>
-->
<p>Dr. Musemeche has been an associate professor of surgery at major medical schools and hospitals and has cared for thousands of critically ill and injured children from newborns to teenagers.</p>

<p><a title="Hurt: the inspiring, untold story of trauma by Catherine Musemeche, M.D." href="images/hurt.jpg" rel="lightbox"><img class="framed imageRight" style="max-width: 175px;" src="images/hurt_sized.jpg" alt="Hurt: the inspiring, untold story of trauma by Catherine Musemeche, M.D."/></a></p>
<p><em><strong>Hurt: the inspiring, untold story of trauma</strong></em> explores the topic of injury from the viewpoint of doctors, rescuers,  patients and their families. HURT walks us through the development of today's advanced trauma centers and demonstrates in graphic detail why they are essential in surviving complex injuries.</p>

<p><a title="Small - Life and Death on the Front Lines of Pediatric Surgery by Catherine Musemeche, M.D." href="images/small_cover.jpg" rel="lightbox"><img class="framed imageLeft" style="max-width: 175px;" src="images/small_cover_sized.jpg" alt="Small - Life and Death on the Front Lines of Pediatric Surgery by Catherine Musemeche, M.D."/></a></p>
<p><em><strong>SMALL: Life and Death on the Front Lines of Pediatric Surgery</strong></em>, Dr. Musemeche's riveting account of life as a pediatric surgeon published by University Press of New England in 2014 has been nominated for the PEN American/E.O. Wilson Literary Science Award.</p>
<p>Dr. Musemeche is also the author of "Wake-Up Call," which was <a title="Excerpt from Twelve Breaths A Minute End of Life Essays. Link opens in new window." href="http://www.npr.org/books/titles/138679026/twelve-breaths-a-minute-end-of-life-essays#excerpt" target="_blank">excerpted on the NPR website</a> and included in <a class="bookLink" title="At the End of Life: True Stories of How We Die - on Amazon - Link opens in new window" href="http://www.amazon.com/At-End-Life-Stories-About/dp/1937163040/ref=sr_1_11?s=books%26ie=UTF8%26qid=1333575839%26sr=1-11" target="_blank">At the End of Life: True Stories of How We Die.</a> Read an&nbsp;<a href="http://attheendoflife.wordpress.com/2012/05/07/seeing-things-that-other-people-cant-see-an-interview-with-catherine-a-musemeche/">Interview about "Wake Up Call.</a>"</p>
<p>Catherine Musemeche is a guest contributor to the <a href="http://parenting.blogs.nytimes.com/2015/04/14/taking-the-torch-from-sarah-brady-why-doctors-need-to-ask-about-guns-in-the-home/?smid=tw-share"><em>New York Times Motherlode</em> column</a>. Her essay, "Lessons," appeared in the journal <a href="https://www.creativenonfiction.org/authors/catherine-musemeche"><em>Creative Nonfiction</em></a>, Sept. 2015.</p>
